media:
  input: public/images
  output: /images
  categories: [ image ]
content:
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    extension: mdx
    fields:
      - name: title
        label: Title
        type: string
      - name: layout
        label: Layout
        type: string
